### ISSUE TITLE
SearchVideos has no attribute timeout

### ISSUE THREAD

**Issue by noobsohail** [alexmercerind/youtube-search-python#121]
```
2021-09-27T10:25:11.437244+00:00 app[worker.1]: 2021-09-27 10:25:11,436 - telethon.client.updates - ERROR - Unhandled exception on download_video
2021-09-27T10:25:11.437251+00:00 app[worker.1]: Traceback (most recent call last):
2021-09-27T10:25:11.437252+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/youtubesearchpython/handlers/requesthandler.py", line 35, in _makeRequest
2021-09-27T10:25:11.437253+00:00 app[worker.1]:     self.response = urlopen(request, timeout=self.timeout).read().decode('utf_8')
2021-09-27T10:25:11.437253+00:00 app[worker.1]: AttributeError: 'SearchVideos' object has no attribute 'timeout'
2021-09-27T10:25:11.437254+00:00 app[worker.1]: 
2021-09-27T10:25:11.437254+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2021-09-27T10:25:11.437255+00:00 app[worker.1]: 
2021-09-27T10:25:11.437255+00:00 app[worker.1]: Traceback (most recent call last):
2021-09-27T10:25:11.437255+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/telethon/client/updates.py", line 443, in _dispatch_update
2021-09-27T10:25:11.437256+00:00 app[worker.1]:     await callback(event)
2021-09-27T10:25:11.437256+00:00 app[worker.1]:   File "/app/ErzaScarlet/modules/songs.py", line 173, in download_video
2021-09-27T10:25:11.437256+00:00 app[worker.1]:     search = SearchVideos(url, offset = 1, mode = "json", max_results = 1)
2021-09-27T10:25:11.437257+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/youtubesearchpython/legacy/__init__.py", line 172, in __init__
2021-09-27T10:25:11.437257+00:00 app[worker.1]:     self._makeRequest()
2021-09-27T10:25:11.437257+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/youtubesearchpython/handlers/requesthandler.py", line 37, in _makeRequest
2021-09-27T10:25:11.437258+00:00 app[worker.1]:     raise Exception('ERROR: Could not make request.')
2021-09-27T10:25:11.437258+00:00 app[worker.1]: Exception: ERROR: Could not make request.
```

https://github.com/noobsohail/ErzaScarlet/blob/main/ErzaScarlet/modules/songs.py ( can you help please )

**Comment by mytja** [comment]
Legacy package is not supported anymore. I released a patch, but we usually don't support it. Please migrate to `VideosSearch` class, since we do support it.
