### ISSUE TITLE
Playlist class doesn't have a good error handling when Playlist doesn't have any videos

### ISSUE THREAD

**Issue by Maple-Elter** [alexmercerind/youtube-search-python#127]
When I try and use the Playlist function with an unlisted playlist from Youtube Music I get this output
```
Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner       
    self.run()
  File "D:\Program Files\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Alucard\Desktop\ytalbumdl-source\ytalbumdl.py", line 245, in url_handler
    videos = Playlist(video_url)
  File "c:\Users\Alucard\Desktop\ytalbumdl-source\youtubesearchpython\extras.py", line 560, in __init__
    self.__playlist.sync_create()
  File "c:\Users\Alucard\Desktop\ytalbumdl-source\youtubesearchpython\core\playlist.py", line 34, in sync_create
    self.post_processing()
  File "c:\Users\Alucard\Desktop\ytalbumdl-source\youtubesearchpython\core\playlist.py", line 25, in post_processing
    self.__getComponents()
  File "c:\Users\Alucard\Desktop\ytalbumdl-source\youtubesearchpython\core\playlist.py", line 118, in __getComponents
    channelrenderer = self.responseSource["sidebar"]["playlistSidebarRenderer"]["items"][1]["playlistSidebarSecondaryInfoRenderer"]["videoOwner"]["videoOwnerRenderer"]
IndexError: list index out of range
```
support for `music.youtube.com` urls would be nice as well

**Comment by Maple-Elter** [comment]
This is weird because I get a full playlist

**Comment by Maple-Elter** [comment]
yeah it seems to be region locking, because if I try and access it with protonvpn in the netherlands it shows no available videos
