### ISSUE TITLE
Playlist Parsing Error

### ISSUE THREAD

**Issue by ankit-sinha-18** [alexmercerind/youtube-search-python#128]
```
2021-10-19T04:29:09.325562+00:00 app[worker.1]: ERROR: Could not parse YouTube response.
2021-10-19T04:29:09.325563+00:00 app[worker.1]: Traceback (most recent call last):
2021-10-19T04:29:09.325565+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/youtubesearchpython/internal/extras.py", line 218, in __parseSource
2021-10-19T04:29:09.325565+00:00 app[worker.1]:     self.responseSource = json.loads(self.response)
2021-10-19T04:29:09.325566+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/json/__init__.py", line 346, in loads
2021-10-19T04:29:09.325566+00:00 app[worker.1]:     return _default_decoder.decode(s)
2021-10-19T04:29:09.325567+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/json/decoder.py", line 337, in decode
2021-10-19T04:29:09.325567+00:00 app[worker.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2021-10-19T04:29:09.325567+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
2021-10-19T04:29:09.325568+00:00 app[worker.1]:     raise JSONDecodeError("Expecting value", s, err.value) from None
2021-10-19T04:29:09.325568+00:00 app[worker.1]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Getting this error in almost all playlist link except the link used in examples of readme.md

i have tried these playlist link:

1. https://www.youtube.com/watch?v=8-OtWif8Z4A&list=PLRBp0Fe2Gpgl6NQzFz1IQOnZfCeoJKflP
2. https://www.youtube.com/watch?v=tr_we5cAUoo&list=PLRBp0Fe2GpgnSrjNdapocrPGub4AAgNdm
3. https://www.youtube.com/watch?v=uEqhviwZwXs&list=PLRBp0Fe2Gpgm44TG57oQNUqxTHuGBeWnq
4. https://www.youtube.com/watch?v=m2JKZh9XIU8&list=PLpIEeUepLM9yPDw2tQ2GgoNgG--afzgBr
5. https://www.youtube.com/watch?v=jOZGD1eoxoE&list=PLT2PUxNJBoeP2lXMRfTI_AljTWuNWD946

**Comment by mytja** [comment]
Playlist links must be as following:
https://www.youtube.com/playlist?list=playlistId
