### ISSUE TITLE
Trying to import Request from ullib breaks lib for Python 2

### ISSUE THREAD

**Issue by heniotierra** [alexmercerind/youtube-search-python#35]
Using python 2, I get this for version 1.3.2. Version 1.3.1 works just fine.
>pi@basiliscus:~ $ python /opt/tboplayer/tboplayer.py
Traceback (most recent call last):
  File "/opt/tboplayer/tboplayer.py", line 75, in <module>
    from youtubesearchpython import SearchVideos
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/__init__.py", line 1, in <module>
    from youtubesearchpython.videos__search import SearchVideos
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/videos__search.py", line 3, in <module>
    from youtubesearchpython.__requesthandler import RequestHandler
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/__requesthandler.py", line 4, in <module>
    from urllib import urlencode, urlopen, Request
ImportError: cannot import name Request

**Comment by alexmercerind** [comment]
Sorry for inconvenience.

**Comment by alexmercerind** [comment]
Hi there!
alexmercerind@10e301f6f2dc16d9f08da00bb09d8d12569936eb

Now after this commit module will use urllib2 on Python 2 for adding headers.
Please let me know if everything works fine now. After that, I'll update the version on PyPI.

Thankyou 🍀.

Also, I'll consider myself fortunate if you tell me if you are able to reproduce [this issue](https://github.com/alexmercerind/youtube-search-python/issues/34) on the latest version.

**Comment by heniotierra** [comment]
Hi, @alexmercerind ,

Now I am getting this:

>Traceback (most recent call last):
  File "tboplayer.py", line 75, in <module>
    from youtubesearchpython import SearchVideos
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/__init__.py", line 1, in <module>
    from youtubesearchpython.videos__search import SearchVideos
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/videos__search.py", line 3, in <module>
    from youtubesearchpython.__requesthandler import RequestHandler
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/__requesthandler.py", line 22
    headers = {"Accept-Language": f"{self.language},en;q=0.9"}

**Comment by alexmercerind** [comment]
@heniotierra 

I see you haven't made all the changes I made.
Please change your following line in your cloned code:
```py
headers = {"Accept-Language": f"{self.language},en;q=0.9"}
```
with this:
```py
headers = {"Accept-Language": self.language + ",en;q=0.9"}
```

I think you probably missed this change. Since, this kind of string formatting does not work in Python 2.
