### ISSUE TITLE
Intermittent httpcore.ConnectTimeout / httpx.ConnectTimeout / Could not make request errors

### ISSUE THREAD

**Issue by radiolondra** [alexmercerind/youtube-search-python#68]
OS: Windows 10
YTS: 1.4.3
Python: 3.7

```
from youtubesearchpython.__future__ import *
....

    def start_search(self):
        s = self.search_input.text
        asyncio.run(self.search_terms(s))

    async def search_terms(self, str):
        self.data = {}
        videoSearch = VideosSearch(str, limit=20)
        results = await videoSearch.next()
        print(results)
        await self.show_data(results)
```

From time to time some errors are raised practically immediately:

```
Traceback (most recent call last):
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpx\_exceptions.py", line 326, in map_exceptions
     yield
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpx\_client.py", line 1497, in _send_single_request
     ext={"timeout": timeout.as_dict()},
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpx\_transports\default.py", line 170, in arequest
     method, url, headers=headers, stream=stream, ext=ext
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 219, in arequest
     method, url, headers=headers, stream=stream, ext=ext
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpcore\_async\connection.py", line 93, in arequest
     self.socket = await self._open_socket(timeout)
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpcore\_async\connection.py", line 124, in _open_socket
     local_address=self.local_address,
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpcore\_backends\auto.py", line 45, in open_tcp_stream
     hostname, port, ssl_context, timeout, local_address=local_address
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpcore\_backends\asyncio.py", line 271, in open_tcp_stream
     stream_reader=stream_reader, stream_writer=stream_writer
   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_86\lib\contextlib.py", line 130, in __exit__
     self.gen.throw(type, value, traceback)
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
     raise to_exc(exc) from None
 httpcore.ConnectTimeout
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\youtubesearchpython\__future__\handlers\requesthandler.py", line 27, in _makeRequest
     json = requestBody,
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpx\_client.py", line 1636, in post
     timeout=timeout,
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpx\_client.py", line 1362, in request
     request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpx\_client.py", line 1401, in send
     history=[],
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpx\_client.py", line 1438, in _send_handling_auth
     history=history,
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpx\_client.py", line 1466, in _send_handling_redirects
     response = await self._send_single_request(request, timeout)
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpx\_client.py", line 1497, in _send_single_request
     ext={"timeout": timeout.as_dict()},
   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_86\lib\contextlib.py", line 130, in __exit__
     self.gen.throw(type, value, traceback)
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\httpx\_exceptions.py", line 343, in map_exceptions
     raise mapped_exc(message, **kwargs) from exc  # type: ignore
 httpx.ConnectTimeout
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "C:/kivy-projects/WeTube-OLD/main.py", line 478, in <module>
     WeTube().run()
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\kivy\base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\kivymd\uix\behaviors\ripplebehavior.py", line 245, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\kivymd\uix\button.py", line 969, in on_touch_up
     return super().on_touch_up(touch)
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\kivy\lang\builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "C:\kivy-projects\WeTube-OLD\contentsearch.kv", line 204, in <module>
     on_release: root.start_search()
   File "C:/kivy-projects/WeTube-OLD/main.py", line 148, in start_search
     asyncio.run(self.search_terms(s))
   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_86\lib\asyncio\runners.py", line 43, in run
     return loop.run_until_complete(main)
   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_86\lib\asyncio\base_events.py", line 579, in run_until_complete
     return future.result()
   File "C:/kivy-projects/WeTube-OLD/main.py", line 154, in search_terms
     results = await videoSearch.next()
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\youtubesearchpython\__future__\internal\search.py", line 29, in next
     await self._makeRequest()
   File "C:\kivy-projects\WeTube\venv\lib\site-packages\youtubesearchpython\__future__\handlers\requesthandler.py", line 31, in _makeRequest
     raise Exception('ERROR: Could not make request.')
 Exception: ERROR: Could not make request.
```

Any idea?

P.S.: If this is really a timeout issue, is there a way to set a custom timeout?

**Comment by alexmercerind** [comment]
Hi there, there isn't a way to set custom timeout. I'm marking this as a "good first issue", you may offer a pull request to add a `timeout` optional parameter to class constructors.
