### ISSUE TITLE
StreamURLFetcher raises exception that PyTube is not installed

### ISSUE THREAD

**Issue by dscrofts** [alexmercerind/youtube-search-python#69]
Hi,

If I try to use the StreamURLFetcher class I get the following error:

```
> python3
Python 3.9.4 (default, Apr  5 2021, 01:47:16)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
> from youtubesearchpython.__future__ import *
> fetcher = StreamURLFetcher()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dan/Library/Python/3.9/lib/python/site-packages/youtubesearchpython/__future__/streamurlfetcher.py", line 32, in __init__
    super().__init__()
  File "/Users/dan/Library/Python/3.9/lib/python/site-packages/youtubesearchpython/__future__/internal/streamurlfetcher.py", line 28, in __init__
    raise Exception('ERROR: PyTube is not installed. To use this functionality of youtube-search-python, PyTube must be installed.')
Exception: ERROR: PyTube is not installed. To use this functionality of youtube-search-python, PyTube must be installed.
```

I already have PyTube installed. Here are the library versions I'm using:
```
> pip3 show pytube
Name: pytube
Version: 10.7.1
Summary: Python 3 library for downloading YouTube Videos.
Home-page: https://github.com/nficano/pytube
Author: Nick Ficano, Harold Martin
Author-email: nficano@gmail.com, harold.martin@gmail.com
License: MIT
Location: /usr/local/lib/python3.9/site-packages
Requires:
Required-by:
> pip3 show youtube-search-python
Name: youtube-search-python
Version: 1.4.3
Summary: Search for YouTube videos, channels & playlists & get video information using link WITHOUT YouTube Data API v3
Home-page: https://github.com/alexmercerind/youtube-search-python
Author: Hitesh Kumar Saini
Author-email: saini123hitesh@gmail.com
License: MIT
Location: /Users/dan/Library/Python/3.9/lib/python/site-packages
Requires: httpx
Required-by:
```

I've tried reinstalling both libraries but can't seem to get it to work.

**Comment by alexmercerind** [comment]
This issue is actually already fixed by @mytja. I'm yet to update PyPI version, thanks for reminding : ).

**Comment by mytja** [comment]
Actually, I also forgot to update asynchronous StreamURLFetcher. Can you do that?

**Comment by dscrofts** [comment]
Thanks for the update!

Yep, the asynchronous StreamURLFetcher is still raising an error in version 1.4.4 (__future__/internal/streamurlfetcher.py, Line 7 needs changing as per @mytja 's fix for the synchronous version). Any chance we could get that fixed and pushed to PyPI?

**Comment by mytja** [comment]
Will do that tomorrow.
You can install latest version from GitHub using this command `pip install git+https://github.com/alexmercerind/youtube-search-python`

**Comment by alexmercerind** [comment]
@dscrofts  I actually messed that up. If you see latest commit, committed wrong changes, apologies. Fixing & publishing new release.

**Comment by alexmercerind** [comment]
okay i force pushed the fix. 1.4.5 will be the one containing this resolution
