### ISSUE TITLE
Exception: ERROR: Could not make request.

### ISSUE THREAD

**Issue by FightMan01** [alexmercerind/youtube-search-python#97]
```py
videosSearch = VideosSearch("video title here", limit = 1, language = 'hu')
videosResult = await videosSearch.next()
```

```
Traceback (most recent call last):
  File "/home/fightman/.local/lib/python3.8/site-packages/youtubesearchpython/__future__/handlers/requesthandler.py", line 19, in _makeRequest
    response = await client.post(
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fightman/fightman01bot/yt.py", line 488, in ytsearch
    videosResult = await videosSearch.next()
  File "/home/fightman/.local/lib/python3.8/site-packages/youtubesearchpython/__future__/internal/search.py", line 30, in next
    await self._makeRequest(timeout = self.timeout)
  File "/home/fightman/.local/lib/python3.8/site-packages/youtubesearchpython/__future__/handlers/requesthandler.py", line 32, in _makeRequest
    raise Exception('ERROR: Could not make request.')
Exception: ERROR: Could not make request.
```

System info:
```
- Python v3.8.10-final
- httpx v0.13.3
- system info: Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021
```

**Comment by mytja** [comment]
Are you able to access YouTube from browser??? It seems to work for me, even on Linux...
![ytsearch3](https://user-images.githubusercontent.com/52399966/127690368-dbe8c0b2-3354-4e68-9f9d-b4188faa602b.PNG)

**Comment by FightMan01** [comment]
Yes, I can access YouTube. Also my discord bot can play music from YouTube.

**Comment by FightMan01** [comment]
Sometimes it works for me as well. Sometimes just doesn't.

**Comment by mytja** [comment]
Hmmm. This is really strange... It should work...
